apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-de-eventos-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata: 
      labels: 
        app: barramento-de-eventos
    spec:
      containers: 
        - name: barramento-de-eventos # '-' significa que é uma coleção.
          image: jonathanmgomes/ecm516-20232-barramento-de-eventos
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1
--- 
apiVersion: v1
kind: Service
metadata: 
  name: barramento-de-eventos-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: barramento-de-eventos
  ports:
    - name: barramento-de-eventos
      protocol: TCP
      port: 10000
      targetPort: 10000