apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-de-eventos-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: barramento-de-eventos
  template:
    metadata: 
      labels: 
        app: barramento-de-eventos
    spec:
      containers: 
        - name: barramento-de-eventos # '-' significa que é uma coleção.
          image: jonathanmgomes/ecm516-20232-barramento-de-eventos
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1