apiVersion: apps/v1
kind: Deployment
metadata:
  name: classificacao-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: classificacao
  template:
    metadata: 
      labels: 
        app: classificacao
    spec:
      containers: 
        - name: classificacao # '-' significa que é uma coleção.
          image: jonathanmgomes/ecm516-20232-classificacao
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1
--- 
apiVersion: v1
kind: Service
metadata: 
  name: classificacao-clusterip-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000
---
apiVersion: v1
kind: Service
metadata: 
  name: classificacao-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000