apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: lembretes
  template:
    metadata: 
      labels: 
        app: lembretes
    spec:
      containers: 
        - name: lembretes # '-' significa que é uma coleção.
          image: jonathanmgomes/ecm516-20232-lembretes
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1
--- 
apiVersion: v1
kind: Service
metadata: 
  name: lembretes-clusterip-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: lembretes
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000