apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: observacoes
  template:
    metadata: 
      labels: 
        app: observacoes
    spec:
      containers: 
        - name: observacoes # '-' significa que é uma coleção.
          image: jonathanmgomes/ecm516-20232-observacoes
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1
--- 
apiVersion: v1
kind: Service
metadata: 
  name: observacoes-clusterip-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: observacoes-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: observacoes
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000